### ISSUE TITLE
Application Refactor

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/therapy-normalization#28]
We are currently writing normalization routines for each normalizer, but we should move to a single datastore for queries going forward.

This will reduce the amount of code we need to test and maintain.

This is a big issue, and will require several components. I am adding the EPIC label to designate this as the top-level issue, and we can track the related tasks on the [Application Refactor project](https://github.com/cancervariants/therapy-normalization/projects/2).

**Comment by ahwagner** [comment]
Issues:
- [ ] Add ORM and define initial schema for db
- [ ] Create ETL methods in normalizer classes
- [ ] Add methods and CLI for populating database
- [ ] Refactor query.py to search db instead of relying on `normalize` routines
