### ISSUE TITLE
Application Refactor: DynamoDB

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/therapy-normalization#45]
Transition from sqlite database to DynamoDB.

We can track the related tasks on the [Application Refactor Project](https://github.com/cancervariants/therapy-normalization/projects/2).

- [ ] ChEMBL ETL methods (#46)
- [ ] Wikidata ETL methods (#47)
- [ ] DrugBank ETL methods (#48)
- [ ] NCIt ETL methods (#49)
- [ ] Refactor query.py (#50)
- [ ] Refactor CLI (#51)
